### PR TITLE
linting and cleaning

### PR DESCRIPTION
**Pull request by ksatirli**
Hey @martinrusev!

thanks for the role; I saw a few things that did not make full sense (like the `.retry` file) and the requirements mis-alignment, so I fixed them

### CODE REVIEW

**Comment by martinrusev** [comment]
Hi @ksatirli !

Thanks for the cleanup. Very welcome additions! 

My plan is to use this one as a blueprint for any future ansible playbooks that will benefit from an Ansible Galaxy release + Travis CI for automatic syntax check/push.

**Comment by ksatirli** [comment]
Hey @martinrusev totally my pleasure!

I'm happy to also add some more tests (in a separate PR) to the role that use Molecule vs. the shell-script approach you have.

See https://github.com/withmethod/ansible-role-google-chrome for an example of this (and specifically: `goss.yml` and `molecule/Default`).

**Comment by martinrusev** [comment]
Hi @ksatirli,

That would be really awesome!

Was not aware of Molecule. For my testing shell script I used a simplified version of the tests in this role https://github.com/geerlingguy/ansible-role-java/tree/master/tests
It is functional, but I don't like it very much.

I use Goss already locally for some playbooks, but so far have not spent the time to make it work with Travis

**Comment by ksatirli** [comment]
Cool, I'll send something your way in a new PR!

**Pull request merged**
